# Site settings
title: "Grey Blog"
description: "你获得的不会超过你的认知"
baseurl: "" 
#change the baseurl to "" if you are using it as your user GitHub Pages
url: "https://Hummmm.github.io"  


# GitHub User settings
username: "Hummmm"
github_username: "Hummmm"
#user_description: user_description
#user_title: user_title
#email: 

# Blog Author settings
author:
  name:"Grey"           
  picture:        
  email:"jiali.wong@outlook.com"         
  description:     
  twitter:
  facebook:
  github:"https://github.com/Hummmm"        
  linkedin:
  clustrmap:      


# markdown
markdown: kramdown
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: true
      status: Completed
      protected: false
      commentable: true
      rss: true
      numbering: true


exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"
